server:
  # 랜덤 포트 사용하기 위해 0으로 설정
  port: 0

spring:
  application:
    name: user-service
  # datasource 설정 정보 공통 프로파일로 위치 변경
  # Messaging Service 설정 정보
  rabbitmq:
    host: 127.0.0.1
    port: 5673
    username: guest
    password: guest

# eureka 서버에 등록할 수 있도록 설정
eureka:
  # 고정 instance_id 를 사용하지 않고 scale-up 되는 경우 인스턴스 구분하기 위함
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    #
    register-with-eureka: true
    #
    fetch-registry: true
    # eureka 서버에 등록하기 위한 url 경로 설정
    service-url:
      # 서버가 가진 위치값을 설정
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce

logging:
  level:
    com:
      example:
        userservice:
          clinet: debug

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
